name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  - ipython
  # sphinx
  - sphinx=6.2.1 # sphinx-design currently requires sphinx[version>=2,<5] # https://github.com/sphinx-doc/sphinx/releases
  # theme and extensions
  - pydata-sphinx-theme=0.13.3 # website theme # https://github.com/pydata/pydata-sphinx-theme/releases
  - myst-parser=2.0.0 # Markdown support # https://github.com/executablebooks/MyST-Parser/releases
  - nbsphinx=0.9.2 # Jupyter notebook support # https://github.com/spatialaudio/nbsphinx/releases
  - sphinx-autoapi=2.1.0 # to build docs from source code instead of package import # https://github.com/readthedocs/sphinx-autoapi/tags
  - sphinx-design=0.4.1 # responsive web component support # https://github.com/executablebooks/sphinx-design/releases
  - sphinx-notfound-page=0.8.3 # custom 404 page # https://github.com/readthedocs/sphinx-notfound-page/tags
  - graphviz=8.0.5 # for plotting dependency diagrams with sphinx-autoapi # https://anaconda.org/conda-forge/graphviz/files
  - sphinx-favicon=1.0.1 # for custom favicons # https://github.com/tcmetzger/sphinx-favicon/releases
  - sphinx-copybutton=0.5.2 # for copy button in code blocks # https://github.com/executablebooks/sphinx-copybutton/releases
  # build process
  - sphinx-autobuild=2021.3.14 # live-html support # https://github.com/executablebooks/sphinx-autobuild/releases