# this workflow re-uses the workflow 'github_action_trigger_submodule_pull_main.yml' in the brightway-documentation repository
name: Create Workflow Dispatch (Trigger Submodule Pull), Re-Use Workflow

jobs:
    build:
    uses:
      brightway-lca/brightway-documentation/.github/workflows/github_action_trigger_submodule_pull_main.yml@main